### ISSUE TITLE
CodeQL: Double escaping or unescaping at `utils/readfiles.js:20`

### ISSUE THREAD

**Issue by ThibaudLopez** [guatedude2/node-readfiles#10]
Title: `Double escaping or unescaping`
File: `utils/readfiles.js:20`
Tool: `CodeQL`
Rule ID: `js/double-escaping`
Query: [View source](https://github.com/github/codeql/blob/8cd261af0ed7edb7cd6b8ea6a0ffd99033b79783/javascript/ql/src/Security/CWE-116/DoubleEscaping.ql)

![image](https://user-images.githubusercontent.com/6137886/173861078-a7e22f03-387b-4fd2-a964-3c968f254cda.png)

**Comment by ThibaudLopez** [comment]
@guatedude2, we applied your fix for #7 #8 and #9, but we still get CodeQL alerts, and this new one about double escaping.

We did a simple test of `buildFilter` with the current directory `.` .

The old code returns true correctly:
```javascript
> buildFilter(".")
/^\/?\.$/i
> buildFilter(".").test(".")
true
```

The new code returns false incorrectly:
```javascript
> buildFilter(".")
/^\/?\\\.$/i
> buildFilter(".").test(".")
false
```

**Comment by guatedude2** [comment]
ah ok I see it

**Comment by guatedude2** [comment]
so I tested this out with the unit tests and seems to be working:

```
  it('creates a filter RegExp given a filter string', () => {
    const result = buildFilter('.');

    expect(result).toEqual(/^\/?\.$/i);
  });
```

passes

**Comment by guatedude2** [comment]
I published version v0.3.1. can you try that version?

**Comment by ThibaudLopez** [comment]
Actually, we had missed [one](https://github.com/guatedude2/node-readfiles/commit/033dda1ec44c38b39cd5debc1c1afb2e41762c86) of your commits. Our test above is returning true now. Thanks

**Comment by guatedude2** [comment]
Great. Let me know if anything else comes up
