### ISSUE TITLE
Incorrect default value for hidden

### ISSUE THREAD

**Issue by CongAn** [guatedude2/node-readfiles#5]
document
> hidden: a boolean value whether to exclude hidden files prefixed with a . (defaults to true)

68 lines of code
```js
          // skip file if it's a hidden file and the hidden option is not set
          if (options.hidden !== true && /^\./.test(filename)) {
            return next();
          }
```

**Comment by guatedude2** [comment]
Thanks for pointing that out. Updated readme:

> hidden: a boolean value whether to include hidden files prefixed with a . (defaults to false)

**Comment by guatedude2** [comment]
Updated in v0.2.1
