### ISSUE TITLE
CodeQL: Incomplete string escaping or encoding @ lib/readfiles.js:13

### ISSUE THREAD

**Issue by ThibaudLopez** [guatedude2/node-readfiles#9]
Hi @guatedude2, following #7 and #8, CodeQL reported another finding (see screenshot below):

- Title: `Incomplete string escaping or encoding`.
- Location: `lib/readfiles.js:13`
- Description: `Sanitizing untrusted input is a common technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.`
- Tool: `CodeQL`
- Rule ID: `js/incomplete-sanitization`

You probably see the same on your CodeQL dashboard.

Is this a true positive or false positive?

Thanks

----

![image](https://user-images.githubusercontent.com/6137886/169324199-423e4481-9f74-4f10-bc6a-29f8f8413e9f.png)

**Comment by guatedude2** [comment]
Refactored library to TypeScript

**Comment by guatedude2** [comment]
duplicate of https://github.com/guatedude2/node-readfiles/issues/8
